export type GalleryCat = "flores" | "plantas" | "eventos";

export type GalleryItem = {
  src: string;
  cat: GalleryCat;
  w: number;
  h: number;
};

// AUTO-GENERATED by scripts/ig-sync.mjs — do not edit by hand.
// Re-run `node scripts/ig-sync.mjs` to refresh from Instagram.
export const GALLERY: GalleryItem[] = [
  { src: "/gallery/plantas_01.jpg", cat: "plantas", w: 1080, h: 1920 },
  { src: "/gallery/plantas_02.jpg", cat: "plantas", w: 1080, h: 1920 },
  { src: "/gallery/plantas_03.jpg", cat: "plantas", w: 1080, h: 1920 },
  { src: "/gallery/plantas_04.jpg", cat: "plantas", w: 1080, h: 1920 },
  { src: "/gallery/plantas_05.jpg", cat: "plantas", w: 1080, h: 1350 },
  { src: "/gallery/plantas_06.jpg", cat: "plantas", w: 1080, h: 1350 },
  { src: "/gallery/plantas_07.jpg", cat: "plantas", w: 1080, h: 1350 },
  { src: "/gallery/plantas_08.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_09.jpg", cat: "plantas", w: 750, h: 1000 },
  { src: "/gallery/plantas_10.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_11.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_12.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_13.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_14.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_15.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_16.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_17.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_18.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_19.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_20.jpg", cat: "plantas", w: 1080, h: 1440 },
  { src: "/gallery/plantas_21.jpg", cat: "plantas", w: 1080, h: 1350 },
  { src: "/gallery/plantas_22.jpg", cat: "plantas", w: 1080, h: 1350 },
  { src: "/gallery/plantas_23.jpg", cat: "plantas", w: 1080, h: 1920 },
  { src: "/gallery/plantas_24.jpg", cat: "plantas", w: 1080, h: 1920 },
  { src: "/gallery/flores_01.jpg", cat: "flores", w: 1080, h: 1350 },
];
