// Instagram content sync for Flores da Poça.
//
// Pulls the public web-profile feed for an Instagram handle and mirrors every
// still image (post covers + carousel children) into /public/gallery, then
// regenerates app/gallery-data.ts so the site's gallery is driven by whatever
// is live on the account.
//
//   node scripts/ig-sync.mjs                 # default handle (floresdapoca)
//   IG_HANDLE=otherhandle node scripts/ig-sync.mjs
//
// Notes:
// - Uses the unauthenticated web_profile_info endpoint (app id 936619743392459).
//   It returns the most recent ~12 posts. That is enough to seed the gallery;
//   re-run whenever the account posts new work.
// - Video posts contribute their cover frame (display_url) as a still.

import { writeFile, mkdir } from "node:fs/promises";
import { createWriteStream } from "node:fs";
import { pipeline } from "node:stream/promises";
import { Readable } from "node:stream";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";

const execFileP = promisify(execFile);

const HANDLE = process.env.IG_HANDLE || "floresdapoca";
const ROOT = path.resolve(import.meta.dirname, "..");
const OUT_DIR = path.join(ROOT, "public", "gallery");
const DATA_FILE = path.join(ROOT, "app", "gallery-data.ts");

const HEADERS = {
  "x-ig-app-id": "936619743392459",
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36",
};

// Keyword buckets → gallery category. First match wins; default is "flores".
const CATEGORY_RULES = [
  { cat: "plantas", re: /planta|garden|zamio|pachira|suculent|verde|folhagem|vaso/i },
  { cat: "eventos", re: /casamento|evento|cerimón|batizado|decora|festa/i },
];

function categorise(caption = "") {
  for (const { cat, re } of CATEGORY_RULES) if (re.test(caption)) return cat;
  return "flores";
}

async function fetchProfile(handle) {
  const url = `https://www.instagram.com/api/v1/users/web_profile_info/?username=${handle}`;
  // Instagram frequently rejects Node's fetch client (HTTP 400) but honours
  // curl with the same headers — so fetch first, fall back to curl.
  try {
    const res = await fetch(url, { headers: HEADERS });
    if (res.ok) return res.json();
    throw new Error(`HTTP ${res.status}`);
  } catch (err) {
    console.log(`  fetch failed (${err.message}) — retrying via curl …`);
    const args = [
      "-s",
      "-H", `x-ig-app-id: ${HEADERS["x-ig-app-id"]}`,
      "-H", `Referer: https://www.instagram.com/${handle}/`,
      "-H", `User-Agent: ${HEADERS["User-Agent"]}`,
      url,
    ];
    const { stdout } = await execFileP("curl", args, {
      maxBuffer: 64 * 1024 * 1024,
    });
    return JSON.parse(stdout);
  }
}

// Flatten a post into one or more still images (post cover + carousel children).
function stillsFromNode(node) {
  const caption =
    node.edge_media_to_caption?.edges?.[0]?.node?.text ?? "";
  const cat = categorise(caption);
  const children = node.edge_sidecar_to_children?.edges;
  const nodes = children ? children.map((e) => e.node) : [node];
  return nodes
    .filter((n) => n.display_url)
    .map((n) => ({
      url: n.display_url,
      w: n.dimensions?.width ?? 1080,
      h: n.dimensions?.height ?? 1080,
      cat,
    }));
}

async function download(url, dest) {
  try {
    const res = await fetch(url, { headers: HEADERS });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    await pipeline(Readable.fromWeb(res.body), createWriteStream(dest));
  } catch {
    // CDN occasionally blocks the Node client — curl mirrors reliably.
    await execFileP("curl", ["-s", "-o", dest, url], {
      maxBuffer: 64 * 1024 * 1024,
    });
  }
}

function toDataFile(items) {
  const lines = items
    .map(
      (it) =>
        `  { src: "${it.src}", cat: "${it.cat}", w: ${it.w}, h: ${it.h} },`
    )
    .join("\n");
  return `export type GalleryCat = "flores" | "plantas" | "eventos";

export type GalleryItem = {
  src: string;
  cat: GalleryCat;
  w: number;
  h: number;
};

// AUTO-GENERATED by scripts/ig-sync.mjs — do not edit by hand.
// Re-run \`node scripts/ig-sync.mjs\` to refresh from Instagram.
export const GALLERY: GalleryItem[] = [
${lines}
];
`;
}

async function main() {
  console.log(`→ fetching @${HANDLE} …`);
  const data = await fetchProfile(HANDLE);
  const user = data?.data?.user;
  if (!user) throw new Error("unexpected response shape (no user)");

  const edges = user.edge_owner_to_timeline_media?.edges ?? [];
  console.log(`  ${user.full_name} · ${edges.length} recent posts`);

  const stills = edges.flatMap((e) => stillsFromNode(e.node));
  console.log(`  ${stills.length} still images to mirror`);

  await mkdir(OUT_DIR, { recursive: true });

  const items = [];
  const counters = {};
  for (const s of stills) {
    counters[s.cat] = (counters[s.cat] ?? 0) + 1;
    const name = `${s.cat}_${String(counters[s.cat]).padStart(2, "0")}.jpg`;
    try {
      await download(s.url, path.join(OUT_DIR, name));
      items.push({ src: `/gallery/${name}`, cat: s.cat, w: s.w, h: s.h });
      process.stdout.write(".");
    } catch (err) {
      process.stdout.write("x");
    }
  }
  console.log(`\n  saved ${items.length} images to public/gallery`);

  await writeFile(DATA_FILE, toDataFile(items));
  console.log(`✓ wrote ${path.relative(ROOT, DATA_FILE)}`);
}

main().catch((err) => {
  console.error("✗", err.message);
  process.exit(1);
});
